"""init

Revision ID: 5d2dc7ba2cfb
Revises: b3adceb55f0f
Create Date: 2020-12-18 17:46:46.987848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2dc7ba2cfb'
down_revision = 'b3adceb55f0f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
