"""init

Revision ID: 54ea2e7c8bc3
Revises: 5d2dc7ba2cfb
Create Date: 2020-12-18 17:55:34.691350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ea2e7c8bc3'
down_revision = '5d2dc7ba2cfb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_master'))
    )
    op.create_table('board_interview_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_interview_map'))
    )
    op.create_table('board_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_master'))
    )
    op.create_table('board_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_status'))
    )
    op.create_table('board_user_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_user_map'))
    )
    op.create_table('document_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_master'))
    )
    op.create_table('guest_date_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_date_map'))
    )
    op.create_table('guest_user_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_user_master'))
    )
    op.create_table('interview_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_master'))
    )
    op.create_table('question_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_master'))
    )
    op.create_table('user_fingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_fingerprint'))
    )
    op.create_table('user_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_master'))
    )
    op.create_table('vo_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vo_answers'))
    )
    op.create_table('vo_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vo_status'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vo_status')
    op.drop_table('vo_answers')
    op.drop_table('user_master')
    op.drop_table('user_fingerprint')
    op.drop_table('question_master')
    op.drop_table('interview_master')
    op.drop_table('guest_user_master')
    op.drop_table('guest_date_map')
    op.drop_table('document_master')
    op.drop_table('board_user_map')
    op.drop_table('board_status')
    op.drop_table('board_master')
    op.drop_table('board_interview_map')
    op.drop_table('answer_master')
    # ### end Alembic commands ###
