"""init

Revision ID: 28c6555d4d9b
Revises: 54ea2e7c8bc3
Create Date: 2020-12-21 10:53:17.542604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c6555d4d9b'
down_revision = '54ea2e7c8bc3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_master', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_answer_master_ques_id_question_master'), 'question_master', ['ques_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('board_interview_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('interview_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_board_interview_map_interview_id_interview_master'), 'interview_master', ['interview_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_board_interview_map_board_id_board_master'), 'board_master', ['board_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('board_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('no_of_members', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subject_name', sa.Text(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('board_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boardmap_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cand_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_board_status_cand_id_candidate_master'), 'candidate_master', ['cand_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_board_status_boardmap_id_board_interview_map'), 'board_interview_map', ['boardmap_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('board_user_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boardmap_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_role', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_board_user_map_boardmap_id_board_interview_map'), 'board_interview_map', ['boardmap_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('document_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_name', sa.Text(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('guest_date_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_guest_date_map_guest_id_guest_user_master'), 'guest_user_master', ['guest_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('guest_user_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phone_no', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.Integer(), nullable=True))

    with op.batch_alter_table('interview_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notification_no', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('to_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question_text', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_master_doc_id_document_master'), 'document_master', ['doc_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user_fingerprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_fingerprint_user_id_user_master'), 'user_master', ['user_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.Integer(), nullable=True))

    with op.batch_alter_table('vo_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ans_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('boardmap_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cand_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ques_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_vo_answers_ques_id_question_master'), 'question_master', ['ques_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vo_answers_ans_id_answer_master'), 'answer_master', ['ans_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vo_answers_boardmap_id_board_interview_map'), 'board_interview_map', ['boardmap_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vo_answers_cand_id_candidate_master'), 'candidate_master', ['cand_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vo_answers_user_id_login_user_master'), 'login_user_master', ['user_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('vo_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boardmap_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cand_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_vo_status_cand_id_candidate_master'), 'candidate_master', ['cand_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vo_status_user_id_login_user_master'), 'login_user_master', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vo_status_boardmap_id_board_interview_map'), 'board_interview_map', ['boardmap_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vo_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_vo_status_boardmap_id_board_interview_map'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vo_status_user_id_login_user_master'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vo_status_cand_id_candidate_master'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')
        batch_op.drop_column('cand_id')
        batch_op.drop_column('boardmap_id')

    with op.batch_alter_table('vo_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_vo_answers_user_id_login_user_master'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vo_answers_cand_id_candidate_master'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vo_answers_boardmap_id_board_interview_map'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vo_answers_ans_id_answer_master'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vo_answers_ques_id_question_master'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('ques_id')
        batch_op.drop_column('cand_id')
        batch_op.drop_column('boardmap_id')
        batch_op.drop_column('ans_id')

    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('status')
        batch_op.drop_column('role')
        batch_op.drop_column('designation')

    with op.batch_alter_table('user_fingerprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_fingerprint_user_id_user_master'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('question_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_question_master_doc_id_document_master'), type_='foreignkey')
        batch_op.drop_column('question_text')
        batch_op.drop_column('doc_id')

    with op.batch_alter_table('interview_master', schema=None) as batch_op:
        batch_op.drop_column('to_date')
        batch_op.drop_column('status')
        batch_op.drop_column('notification_no')
        batch_op.drop_column('from_date')

    with op.batch_alter_table('guest_user_master', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('status')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('email')

    with op.batch_alter_table('guest_date_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_guest_date_map_guest_id_guest_user_master'), type_='foreignkey')
        batch_op.drop_column('to_date')
        batch_op.drop_column('guest_id')
        batch_op.drop_column('from_date')

    with op.batch_alter_table('document_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_column('doc_name')

    with op.batch_alter_table('board_user_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_board_user_map_boardmap_id_board_interview_map'), type_='foreignkey')
        batch_op.drop_column('user_role')
        batch_op.drop_column('user_id')
        batch_op.drop_column('boardmap_id')

    with op.batch_alter_table('board_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_board_status_boardmap_id_board_interview_map'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_board_status_cand_id_candidate_master'), type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('marks')
        batch_op.drop_column('cand_id')
        batch_op.drop_column('boardmap_id')

    with op.batch_alter_table('board_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_column('subject_name')
        batch_op.drop_column('status')
        batch_op.drop_column('password')
        batch_op.drop_column('no_of_members')
        batch_op.drop_column('login_id')

    with op.batch_alter_table('board_interview_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_board_interview_map_board_id_board_master'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_board_interview_map_interview_id_interview_master'), type_='foreignkey')
        batch_op.drop_column('interview_id')
        batch_op.drop_column('date')
        batch_op.drop_column('board_id')

    with op.batch_alter_table('answer_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_answer_master_ques_id_question_master'), type_='foreignkey')

    # ### end Alembic commands ###
